language: go

matrix:
  fast_finish: true
  include:
  - go: 1.13.x
  - go: 1.14.x

git:
  depth: 10

install:
  - go get -u golang.org/x/lint/golint

script:
  - go mod vendor
  - make vet
  - make lint
  - make test
