site_name: Gasper
site_description: Gasper Documentation
site_author: SDSLabs
# site_url: https://github.com/sdslabs/gasper
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/sdslabs/gasper'

docs_dir: 'content'

theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  favicon: assets/logo/gasperlogo.svg
  logo: assets/logo/docs-logo.png
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'indigo'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; SDSLabs"

extra_css:
  - assets/css/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/js/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false # hljs is used instead of pygment for TOML highlighting support
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
